dirinput_pp<- paste0(thisdir,"/input_pp/")
dirinput_pp_subfolder1<- paste0(thisdir,"/input_pp/D4 tables")
dirinput_pp_subfolder2<- paste0(thisdir,"/input_pp/dashboard tables")

suppressWarnings(if (!file.exists(dirinput_pp)) dir.create(file.path( dirinput_pp)))
suppressWarnings(if (!file.exists(dirinput_pp_subfolder1)) dir.create(file.path( dirinput_pp_subfolder1)))
suppressWarnings(if (!file.exists(dirinput_pp_subfolder2)) dir.create(file.path( dirinput_pp_subfolder2)))

# load packages
if (!require("haven")) install.packages("haven")
library(haven)
if (!require("tidyverse")) install.packages("tidyverse")
library(dplyr)
if (!require("lubridate")) install.packages("lubridate")
library(lubridate)
if (!require("data.table")) install.packages("data.table")
library(data.table)
if (!require("AdhereR")) install.packages("AdhereR")
library(AdhereR)
if (!require("stringr")) install.packages("stringr")
library(stringr)
if (!require("purrr")) install.packages("purrr")
library(purrr)
if (!require("readr")) install.packages("readr")
library(readr)
if (!require("dplyr")) install.packages("dplyr")
library(dplyr)
if (!require("survival")) install.packages("survival")
library(survival)

#############
`%not in%` <- negate(`%in%`)
